### ISSUE TITLE
giab's variant caller error issue

### ISSUE THREAD

**Issue by Logan-Kang** [allenday/dataflow-genomics#39]
We ran the java cp command. However, the following error occurred and I don't know the cause.
(giab-example)

java -cp target/giab-example-1.0.0.jar \
     com.google.allenday.genomics.core.example.GiabExampleApp \
         --project=$PROJECT_ID \
         --runner=DataflowRunner \
         --region=$REGION \
         --inputCsvUri=$CSV_URI \
         --workerMachineType=$MACHINE_TYPE \
         --maxNumWorkers=$MAX_WORKERS \
         --numWorkers=$MAX_WORKERS \
         --diskSizeGb=$DISK_SIZE \
         --stagingLocation=$STAGING_LOC \
         --tempLocation=$TEMP_LOC \
         --srcBucket=$SRC_BUCKET_NAME \
         --refDataJsonString=$REFERENCE_DATA_JSON_STRING \
         --outputGcsUri=$OUTPUT_GCS_URI \
         --variantCaller=$VARIENT_CALLER \
         --controlPipelineWorkerRegion=$CONTROL_PIPELIE_WORKER_REGION \
         --stepsWorkerRegion=$STEPS_WORKER_REGION \
         --makeExamplesCoresPerWorker=$M_E_CORES \
         --makeExamplesRamPerWorker=$M_E_MEMORY \
         --makeExamplesDiskPerWorker=$M_E_DISK \
         --callVariantsCoresPerWorker=$C_V_CORES \
         --callVariantsRamPerWorker=$C_V_MEMORY \
         --callVariantsDiskPerWorker=$C_V_DISK \
         --postprocessVariantsCores=$P_V_CORES \
         --postprocessVariantsRam=$P_V_MEMORY \
         --postprocessVariantsDisk=$P_V_DISK \
         --makeExamplesWorkers=$M_E_WORKERS \
         --callVariantsWorkers=$C_V_WORKERS \
         --deepVariantShards=$M_E_SHARDS \
         --exportVcfToBq=False

Exception in thread "main" java.lang.IllegalArgumentException: Empty argument value is only allowed for String, String Array, Collections of Strings or any of these types in a parameterized ValueProvider, but received: class com.google.allenday.genomics.core.model.VariantCaller
        at org.apache.beam.sdk.options.PipelineOptionsFactory.checkEmptyStringAllowed(PipelineOptionsFactory.java:1781)
        at org.apache.beam.sdk.options.PipelineOptionsFactory.parseObjects(PipelineOptionsFactory.java:1681)
        at org.apache.beam.sdk.options.PipelineOptionsFactory.access$400(PipelineOptionsFactory.java:115)
        at org.apache.beam.sdk.options.PipelineOptionsFactory$Builder.as(PipelineOptionsFactory.java:298)
        at com.google.allenday.genomics.core.example.GiabExampleApp.main(GiabExampleApp.java:25)

**Comment by pseveryn** [comment]
@Logan-Kang , it's not clear, what exactly you have passed into `--variantCaller` parameter. You can try with an updated doc from https://github.com/allenday/dataflow-genomics/pull/40
Note: if you want to use GATK HaplotypeCaller there is no need to specify `--variantCaller` parameter. GATK will be used by default

**Comment by Logan-Kang** [comment]
+@allenday
@Pseverin , We were informed that allen had modified this and that testing was possible. So I ran the test but got this error. It is important to convert to GATK.

**Comment by pseveryn** [comment]
Hi @Logan-Kang . Please, check what exactly you pass with $VARIENT_CALLER  variable. It looks like you passed an empty String. Also as I mentioned previously, you may remove `--variantCaller` argument if you are planning to use GATK Haplotype Caller

**Comment by pseveryn** [comment]
@Logan-Kang You can use [this doc's section ](https://github.com/allenday/dataflow-genomics/blob/master/giab-example/README.md#running-pipeline) as an example of running the pipeline
