### ISSUE TITLE
0417_giab varient calling error

### ISSUE THREAD

**Issue by Logan-Kang** [allenday/dataflow-genomics#43]
We ran it with the example code from giab's readme.md file, but an error occurred during varient calling.

The dataflow job ran fine, but part failed in [Variant Calling / Reshuffle.ViaRandomKey / Reshuffle / GroupByKey] in progress.

Here is the code I ran.

-----
java -cp target/giab-example-1.0.0.jar \
    com.google.allenday.genomics.core.example.GiabExampleApp \
        --project=gcgpoc \
        --runner=DataflowRunner \
        --region="us-central1" \
        --inputCsvUri="gs://${SRC_BUCKET_NAME}/sra_csv/reads_giab_wgs.csv" \
        --workerMachineType=n1-highmem-4 \
        --maxNumWorkers=69 \
        --numWorkers=2 \
        --diskSizeGb=100 \
        --experiments=shuffle_mode=service \
        --stagingLocation="gs://${WORKING_BUCKET_NAME}/dataflow/staging/" \
        --tempLocation="gs://${WORKING_BUCKET_NAME}/dataflow/temp/" \
        --srcBucket=$SRC_BUCKET_NAME \
        --refDataJsonString=$REFERENCE_DATA_JSON_STRING \
        --outputGcsUri="gs://${WORKING_BUCKET_NAME}/processing_output/" \
        --vcfBqDatasetAndTablePattern="giab.GENOMICS_VARIATIONS_%s" \
        --withFinalMerge=false \
        --fastqExt=FQ

-----

error details:

2020-04-17 07:02:14.805 JST textPayload: "Error message from worker: java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.lang.RuntimeException: Exited with error code: 2. Command: ./gatk-4.1.6.0/gatk HaplotypeCaller -R gs://gcgpoc-src-jp-wgs/reference/GRCh38_latest_genomic.fna -I gs://gcgpoc-working-jp/processing_output/2020-04-16--09-07-53-UTC/intermediate/intermediate/merged_regions_bam/NA12878_grch38_latest_genomic_nt_187632_1_1_186262.merged.sorted.bam -L NT_187632.1:1-186262 -O gs://gcgpoc-working-jp/processing_output/2020-04-16--09-07-53-UTC/final/result_variant_calling/NA12878_GRCh38_latest_genomic/NA12878_grch38_latest_genomic_nt_187632_1_1_186262.vcf --create-output-variant-index=False
	org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:184)
	org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner$1.outputWindowedValue(GroupAlsoByWindowFnRunner.java:107)
	org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowReshuffleFn.processElement(BatchGroupAlsoByWindowReshuffleFn.java:56)
	org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowReshuffleFn.processElement(BatchGroupAlsoByWindowReshuffleFn.java:39)
	org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:120)
	org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73)
	org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:114)
	org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
	org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
	org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201)
	org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159)
	org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:77)
	org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:412)
	org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:381)
	org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:306)
	org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:140)
	org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:120)
	org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:107)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.beam.sdk.util.UserCodeException: java.lang.RuntimeException: Exited with error code: 2. Command: ./gatk-4.1.6.0/gatk HaplotypeCaller -R gs://gcgpoc-src-jp-wgs/reference/GRCh38_latest_genomic.fna -I gs://gcgpoc-working-jp/processing_output/2020-04-16--09-07-53-UTC/intermediate/intermediate/merged_regions_bam/NA12878_grch38_latest_genomic_nt_187632_1_1_186262.merged.sorted.bam -L NT_187632.1:1-186262 -O gs://gcgpoc-working-jp/processing_output/2020-04-16--09-07-53-UTC/final/result_variant_calling/NA12878_GRCh38_latest_genomic/NA12878_grch38_latest_genomic_nt_187632_1_1_186262.vcf --create-output-variant-index=False
	org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:36)
	com.google.allenday.genomics.core.processing.variantcall.VariantCallingFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:224)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:185)
	org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:335)
	org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
	org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
	org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:280)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:258)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:78)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:627)
	org.apache.beam.sdk.transforms.DoFnOutputReceivers$WindowedContextOutputReceiver.output(DoFnOutputReceivers.java:73)
	org.apache.beam.sdk.transforms.MapElements$1.processElement(MapElements.java:139)
	org.apache.beam.sdk.transforms.MapElements$1$DoFnInvoker.invokeProcessElement(Unknown Source)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:224)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:185)
	org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:335)
	org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
	org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
	org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:280)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:258)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:78)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:627)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:615)
	org.apache.beam.runners.dataflow.ReshuffleOverrideFactory$ReshuffleWithOnlyTrigger$1.processElement(ReshuffleOverrideFactory.java:86)
	org.apache.beam.runners.dataflow.ReshuffleOverrideFactory$ReshuffleWithOnlyTrigger$1$DoFnInvoker.invokeProcessElement(Unknown Source)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:224)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:185)
	org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:335)
	org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
	org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
	org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:182)
	... 21 more
Caused by: java.lang.RuntimeException: Exited with error code: 2. Command: ./gatk-4.1.6.0/gatk HaplotypeCaller -R gs://gcgpoc-src-jp-wgs/reference/GRCh38_latest_genomic.fna -I gs://gcgpoc-working-jp/processing_output/2020-04-16--09-07-53-UTC/intermediate/intermediate/merged_regions_bam/NA12878_grch38_latest_genomic_nt_187632_1_1_186262.merged.sorted.bam -L NT_187632.1:1-186262 -O gs://gcgpoc-working-jp/processing_output/2020-04-16--09-07-53-UTC/final/result_variant_calling/NA12878_GRCh38_latest_genomic/NA12878_grch38_latest_genomic_nt_187632_1_1_186262.vcf --create-output-variant-index=False
	com.google.allenday.genomics.core.cmd.CmdExecutor.executeCommand(CmdExecutor.java:79)
	com.google.allenday.genomics.core.cmd.CmdExecutor.executeCommand(CmdExecutor.java:77)
	com.google.allenday.genomics.core.cmd.CmdExecutor.executeCommand(CmdExecutor.java:77)
	com.google.allenday.genomics.core.cmd.CmdExecutor.executeCommand(CmdExecutor.java:77)
	com.google.allenday.genomics.core.cmd.CmdExecutor.executeCommand(CmdExecutor.java:39)
	com.google.allenday.genomics.core.processing.variantcall.GATKService.processSampleWithVariantCaller(GATKService.java:64)
	com.google.allenday.genomics.core.processing.variantcall.VariantCallingFn.processElement(VariantCallingFn.java:75)
" 

2020-04-17 07:02:14.918 JST textPayload: "Workflow failed. Causes: S17:Variant Calling/Reshuffle.ViaRandomKey/Reshuffle/GroupByKey/Read+Variant Calling/Reshuffle.ViaRandomKey/Reshuffle/GroupByKey/GroupByWindow+Variant Calling/Reshuffle.ViaRandomKey/Reshuffle/ExpandIterable+Variant Calling/Reshuffle.ViaRandomKey/Values/Values/Map+Variant Calling/Variant Calling Fn+Prepare and execute export to BigQuery/Prepare for group by VCF output dir/Map+Prepare and execute export to BigQuery/Group by VCF output dir/Reify+Prepare and execute export to BigQuery/Group by VCF output dir/Write failed., The job failed because a work item has failed 4 times. Look in previous log entries for the cause of each one of the 4 failures. For more information, see https://cloud.google.com/dataflow/docs/guides/common-errors. The work item was attempted on these workers: 
  giab-example-processing-2-04160208-6hje-harness-j7w5
      Root cause: Work item failed.,
  giab-example-processing-2-04160208-6hje-harness-j7w5
      Root cause: Work item failed.,
  giab-example-processing-2-04160208-6hje-harness-j7w5
      Root cause: Work item failed.,
  giab-example-processing-2-04160208-6hje-harness-j7w5
      Root cause: Work item failed."  
 timestamp: "2020-04-16T22:02:14.918098364Z" 

-----
Am I wrong?
Need to add permission to bigquery dataset?

**Comment by pseveryn** [comment]
@Logan-Kang , I see that GATK HaplotypeCaller failed 4 times with error code 2.
Could you please list the content of `gs://gcgpoc-src-jp-wgs/reference/` ?

**Comment by Logan-Kang** [comment]
@Pseverin, This bucket folder has two files:
 GRCh38_latest_genomic.fna	
 GRCh38_latest_genomic.fna.fai

**Comment by pseveryn** [comment]
@Logan-Kang ,
GATK HaplotypeCaller failed because you don't have `.dict` file. It described here https://github.com/allenday/dataflow-genomics/tree/master/giab-example#optional-retrieving-data-from-the-original-sources
OR
you can simply copy the content of `gs://dataflow-genomics-giab-demo/reference/` with:
`gsutil -u ${PROJECT_ID} cp -r gs://dataflow-genomics-giab-demo/reference gs://${SRC_BUCKET_NAME}/`

Looking forward to your processing completion update after resolving `.dict` problem

**Comment by Logan-Kang** [comment]
@Pseverin ,
It worked out well through the method you gave me. Thanks.
